sudo: required

language: generic

sevices:
  - docker

before_install:
  - echo "start creating image with dockerfile"
  - docker build -t dennis9352/calories_backend/calories:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true dennis9352/calories_backend/calories:latest npm run test -- --coverage

after_success:
  - echo "Test Success"