sudo: required

language: generic

sevices:
  - docker

before_install:
  - echo "start image"
  - docker build -t dennis9352/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true dennis9352/wodw npm run test --

after_success:
  - echo "success"